deploy:
  provider: s3
  access_key_id: AKIAJYIYMIBE7PCGV72A
  secret_access_key:
    secure: IUvp+ZP45+XIDzFwh5STo6gbUN1IxhRTppAEF9pnIZgLxwnzLQg/OuJwnPFp+ZxQ3/MH1k2ZL6axZ2CCqNtzrp3pRs7wFOSFDSxMduEoKmAOG9fIC5N4WrXlTrA4/f4xADnStnzUdwVsMQ8xzZA0T1LkZsx5Lka9nzJndzTF8zQwnK3XW3G6/IRfQ2ZgSKgb7nbW/hcy/swuRSVUjfZlpjGzvKX5z7Pkcqwfyza98KovD73yyvI4RjKRlSULVupf9maA+SUoa6O0KxWFF4QPuYoRshRrUrdi32DZJKXHgmsXshg40EEGbU97CtiKfHPSeOISfW7awgeGb7B/d8LMmH8XbEGi+7wQN1VWEvkvAoeOnAKwuK0+a3UB6xcGLqyhs5ujA87FdX22wE+hwN0NGQMbQWGlvxiF5JwSL+bLva76BtgCRWLV6PyngWJrIjd+eQlxQkJ/9T9MohAEyUylewITa9BdcLjaCR8hRtV3ZcOtsXdxbSePb+LtTWkAZf1YQyL9D4J7Vy1h5Ekrwch/9grjRONkw79SissDrd5K4I22krW/zoKAMxJlxk/W6QCtLYJVMY/NZpQcIOvdhYdxG31WUieQZNFMP+liJ057MudHJ3Bx4TDS8Lq/nCDaXIoQ0MlX/OFbZGEedD2YI++AqYCMd7wnVQABaiuSoaAaFlM=
  bucket: iot-interface

language: node_js
node_js:
  - node
before_deploy:
  -mkdir -p dpl_cd_upload
